dataset:
  name: tiny_inat
  num_classes: 200
  pre_size: 256
  image_size: 224

  interpolation: bilinear
  normalization_type: imagenet

  num_workers: '@{num_workers}'
  num_gpus: '@{num_gpus}'
  num_machines: '@{num_machines}'

  split_names: [train, val, test]

  train:
    dataset_class: ImglistDataset
    data_dir: ./data/images/
    imglist_pth: ./data/imglist/train_tiny_inat.txt
    batch_size: 4
    shuffle: False
  val:
    dataset_class: ImglistDataset
    data_dir: ./data/images/
    imglist_pth: ./data/imglist/val_tiny_inat.txt
    batch_size: 4
    shuffle: False
  test:
    dataset_class: ImglistDataset
    data_dir: ./data/images/
    imglist_pth: ./data/imglist/val_tiny_inat.txt
    batch_size: 4
    shuffle: False
